/*
 * Copyright (C) Sefer Ergün
 * 
 * Author: Sefer Ergün
 * 
 * Last Update: 05.02.2013
 */
 
#include <rhKernel/rhKernel.h>

#define MAX_KERNEL_PANIC 1024
char buff[MAX_KERNEL_PANIC];

//Generated by http://ascii.co.uk/text
const char *panicText = {
"               [.......        [.       [...     [..[..    [..   \n"
"               [..    [..     [. ..     [. [..   [..[.. [..   [..\n"
"               [..    [..    [.  [..    [.. [..  [..[..[..       \n"
"               [.......     [..   [..   [..  [.. [..[..[..       \n"
"               [..         [...... [..  [..   [. [..[..[..       \n"
"               [..        [..       [.. [..    [. ..[.. [..   [..\n"
"               [..       [..         [..[..      [..[..   [....  \n"
};
int panic_do(const char *_fmt,const char *_file,uint32_t _line,const char *_func,...)
{
	if(_fmt == NULL)
	{
		return;
	}
	setTextColor(WHITE,RED);
	clearScr();
	moveCur(0,0);
	printf(panicText);
	printf("PANIC!\n");
	printf("--------------------------------------------------------------------------------");
	va_list val;
	va_start(val,_fmt);
	if(vsprintf(buff,_fmt,val) < 0)
	{
		return;
	}
	va_end(val);
	printf("%s \nat %s line %i in %s()\n",buff,_file,_line,_func);
	printf("--------------------------------------------------------------------------------");
	printf("System Halted!\n");
	asm("cli");
	asm("hlt");
}
	 
	 
